title: Ch'ti JUG
description: El groupe Java din ch'Nord ed' la France
theme: minima
exclude:
  - Gemfile
url: https://chtijug.github.io
disqus:
  shortname: chtijug
twitter_username: chtijug
github_username: chtijug
youtube_username: "@chtijug"
youtube_channel_name: Ch'ti JUG
linkedin_companyname: chtijug
meetup_groupname: chtijug
author:
  name: La Team Ch'ti JUG
