title: Ch'ti JUG
description: El groupe Java din ch'Nord ed' la France
theme: minima
exclude:
  - Gemfile

disqus:
  shortname: chtijug
minima:
  social_links:
    twitter: chtijug
    github: chtijug
